/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pbolanjut;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Menu_utama extends javax.swing.JFrame {

    /**
     * Creates new form Menu_utama
     */
    
    private Connection conn;
    
    public Menu_utama(String username) {
        initComponents();
        conn = Koneksi.getConnection();
        
        txt_profil.setText("Welcome " + username);
        ResizeImage.setImageToLabel(pnblogo, "/pbolanjut/img/Logo-Politeknik-Negeri-Bali.png", 100, 100);
        
        pn_mahasiswaNonAktif();
        btnNonAktif();
        getData();
        
    }
    
    private void getData() {
        DefaultTableModel model = new DefaultTableModel(
        null, new Object[]{"id", "Nama", "NIM", "Jurusan", "Alamat"});
        
        tb_mahasiswa.setModel(model);
        model.getDataVector().removeAllElements();
        
        try {
            String query = "SELECT * FROM mahasiswa";
            PreparedStatement pst = conn.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()) {
                Object[] data = {
                    rs.getInt("id_mahasiswa"),
                    rs.getString("nama_mahasiswa"),
                    rs.getString("nim"),
                    rs.getString("jurusan"),
                    rs.getString("alamat")
                };
                model.addRow(data);
                
                tb_mahasiswa.getColumnModel().getColumn(0).setMinWidth(0);
                tb_mahasiswa.getColumnModel().getColumn(0).setMaxWidth(0);
                tb_mahasiswa.getColumnModel().getColumn(0).setWidth(0);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void resetData() {
        jNama.setText("");
        jNim.setText("");
        jAlamat.setText("");
    }
    
    private void btnNonAktif() {
        btn_edit.setEnabled(false);
        btn_hapus.setEnabled(false);
    }
    
    private void btnAktif() {
        btn_tambah.setEnabled(true);
        btn_batal.setEnabled(true);
    }
    
    private void pn_mahasiswaNonAktif() {
        jNama.setVisible(false);
        jNim.setVisible(false);
        jJurusan.setVisible(false);
        jAlamat.setVisible(false);
        btn_tambah.setVisible(false);
        btn_edit.setVisible(false);
        btn_batal.setVisible(false);
        btn_hapus.setVisible(false);
        tb_mahasiswa.setVisible(false);
        jScrollPane1.setVisible(false);
        jCari.setVisible(false);
    }
    
    private void pn_mahasiswaAktif() {
        jNama.setVisible(true);
        jNim.setVisible(true);
        jJurusan.setVisible(true);
        jAlamat.setVisible(true);
        btn_tambah.setVisible(true);
        btn_edit.setVisible(true);
        btn_batal.setVisible(true);
        btn_hapus.setVisible(true);
        tb_mahasiswa.setVisible(true);
        jCari.setVisible(true);
        jScrollPane1.setVisible(true);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        pnblogo = new javax.swing.JLabel();
        name_website = new javax.swing.JLabel();
        btn_maximize = new javax.swing.JLabel();
        btn_minimize = new javax.swing.JLabel();
        sidebar = new javax.swing.JPanel();
        btn_profil = new javax.swing.JButton();
        btn_nilai = new javax.swing.JButton();
        btn_mahasiswa = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        content = new javax.swing.JPanel();
        pn_profil = new javax.swing.JPanel();
        txt_profil = new javax.swing.JLabel();
        pn_nilai = new javax.swing.JPanel();
        txt_nilai = new javax.swing.JLabel();
        pn_mahasiswa = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jNama = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jNim = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jJurusan = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jAlamat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btn_tambah = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jCari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_mahasiswa = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        header.setBackground(new java.awt.Color(0, 153, 153));

        pnblogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbolanjut/img/Logo-Politeknik-Negeri-Bali.png"))); // NOI18N

        name_website.setBackground(new java.awt.Color(153, 153, 153));
        name_website.setFont(new java.awt.Font("Kristen ITC", 1, 29)); // NOI18N
        name_website.setForeground(new java.awt.Color(255, 255, 102));
        name_website.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name_website.setText("PNB WEBSITE CUY");
        name_website.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btn_maximize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbolanjut/img/maximize.png"))); // NOI18N
        btn_maximize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_maximizeMouseClicked(evt);
            }
        });

        btn_minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbolanjut/img/minus.png"))); // NOI18N
        btn_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_minimizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(pnblogo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_minimize)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_maximize)
                        .addContainerGap())
                    .addGroup(headerLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(name_website, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(278, Short.MAX_VALUE))))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnblogo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_maximize)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addComponent(btn_minimize)
                        .addGap(11, 11, 11)
                        .addComponent(name_website)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(header, java.awt.BorderLayout.PAGE_START);

        sidebar.setBackground(new java.awt.Color(204, 204, 204));

        btn_profil.setBackground(new java.awt.Color(255, 255, 255));
        btn_profil.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btn_profil.setForeground(new java.awt.Color(153, 153, 153));
        btn_profil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbolanjut/img/user.png"))); // NOI18N
        btn_profil.setText("Profil");
        btn_profil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_profilActionPerformed(evt);
            }
        });

        btn_nilai.setBackground(new java.awt.Color(255, 255, 255));
        btn_nilai.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btn_nilai.setForeground(new java.awt.Color(153, 153, 153));
        btn_nilai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbolanjut/img/point.png"))); // NOI18N
        btn_nilai.setText("Nilai");
        btn_nilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nilaiActionPerformed(evt);
            }
        });

        btn_mahasiswa.setBackground(new java.awt.Color(255, 255, 255));
        btn_mahasiswa.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        btn_mahasiswa.setForeground(new java.awt.Color(153, 153, 153));
        btn_mahasiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbolanjut/img/open-book.png"))); // NOI18N
        btn_mahasiswa.setText("Mahasiswa");
        btn_mahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mahasiswaActionPerformed(evt);
            }
        });

        btn_logout.setBackground(new java.awt.Color(255, 255, 255));
        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbolanjut/img/logout.png"))); // NOI18N
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        btn_exit.setBackground(new java.awt.Color(255, 255, 255));
        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbolanjut/img/cross.png"))); // NOI18N
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_mahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_profil, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_nilai, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebarLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebarLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(btn_profil, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btn_nilai, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btn_mahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        getContentPane().add(sidebar, java.awt.BorderLayout.LINE_START);

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setPreferredSize(new java.awt.Dimension(900, 554));

        pn_profil.setBackground(new java.awt.Color(255, 255, 255));
        pn_profil.setPreferredSize(new java.awt.Dimension(900, 554));

        txt_profil.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        txt_profil.setForeground(new java.awt.Color(0, 0, 0));
        txt_profil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_profil.setText("PROFIL");

        javax.swing.GroupLayout pn_profilLayout = new javax.swing.GroupLayout(pn_profil);
        pn_profil.setLayout(pn_profilLayout);
        pn_profilLayout.setHorizontalGroup(
            pn_profilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_profilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_profil, javax.swing.GroupLayout.DEFAULT_SIZE, 894, Short.MAX_VALUE))
        );
        pn_profilLayout.setVerticalGroup(
            pn_profilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_profilLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(txt_profil, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(214, Short.MAX_VALUE))
        );

        pn_nilai.setBackground(new java.awt.Color(255, 204, 204));
        pn_nilai.setPreferredSize(new java.awt.Dimension(900, 554));

        txt_nilai.setBackground(new java.awt.Color(255, 255, 255));
        txt_nilai.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        txt_nilai.setForeground(new java.awt.Color(0, 0, 0));
        txt_nilai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_nilai.setText("NILAI");

        javax.swing.GroupLayout pn_nilaiLayout = new javax.swing.GroupLayout(pn_nilai);
        pn_nilai.setLayout(pn_nilaiLayout);
        pn_nilaiLayout.setHorizontalGroup(
            pn_nilaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_nilaiLayout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(txt_nilai, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(420, Short.MAX_VALUE))
        );
        pn_nilaiLayout.setVerticalGroup(
            pn_nilaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_nilaiLayout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(txt_nilai, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(269, Short.MAX_VALUE))
        );

        pn_mahasiswa.setBackground(new java.awt.Color(255, 255, 204));

        jPanel6.setBackground(new java.awt.Color(255, 255, 204));
        jPanel6.setPreferredSize(new java.awt.Dimension(300, 554));
        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("FORM MAHASISWA");
        jPanel6.add(jLabel1);

        jPanel7.setBackground(new java.awt.Color(255, 255, 204));
        jPanel7.setPreferredSize(new java.awt.Dimension(300, 240));
        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new java.awt.BorderLayout(0, 5));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("NAMA");
        jPanel1.add(jLabel2, java.awt.BorderLayout.CENTER);

        jNama.setBackground(new java.awt.Color(255, 255, 255));
        jNama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jNama.setPreferredSize(new java.awt.Dimension(215, 26));
        jNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNamaActionPerformed(evt);
            }
        });
        jPanel1.add(jNama, java.awt.BorderLayout.PAGE_END);

        jPanel7.add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setLayout(new java.awt.BorderLayout(0, 5));

        jNim.setBackground(new java.awt.Color(255, 255, 255));
        jNim.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jNim.setPreferredSize(new java.awt.Dimension(215, 26));
        jPanel2.add(jNim, java.awt.BorderLayout.CENTER);

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("NIM");
        jPanel2.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        jPanel7.add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setLayout(new java.awt.BorderLayout(0, 5));

        jJurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Teknologi Informasi", "Teknik Perkapalan", "Teknik Mesin", "Teknik Kedokteran" }));
        jJurusan.setPreferredSize(new java.awt.Dimension(215, 26));
        jJurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jJurusanActionPerformed(evt);
            }
        });
        jPanel3.add(jJurusan, java.awt.BorderLayout.CENTER);

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("JURUSAN");
        jPanel3.add(jLabel4, java.awt.BorderLayout.PAGE_START);

        jPanel7.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));
        jPanel4.setLayout(new java.awt.BorderLayout(0, 5));

        jAlamat.setBackground(new java.awt.Color(255, 255, 255));
        jAlamat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jAlamat.setPreferredSize(new java.awt.Dimension(215, 26));
        jPanel4.add(jAlamat, java.awt.BorderLayout.CENTER);

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("ALAMAT");
        jPanel4.add(jLabel5, java.awt.BorderLayout.PAGE_START);

        jPanel7.add(jPanel4);

        jPanel6.add(jPanel7);

        jPanel5.setBackground(new java.awt.Color(255, 255, 204));
        jPanel5.setLayout(new java.awt.GridLayout(2, 0, 16, 10));

        btn_tambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_tambah.setText("Tambah");
        btn_tambah.setPreferredSize(new java.awt.Dimension(100, 40));
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });
        jPanel5.add(btn_tambah);

        btn_batal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_batal.setText("Batal");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });
        jPanel5.add(btn_batal);

        btn_edit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        jPanel5.add(btn_edit);

        btn_hapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        jPanel5.add(btn_hapus);

        jPanel6.add(jPanel5);

        jPanel9.setBackground(new java.awt.Color(255, 255, 204));
        jPanel9.setPreferredSize(new java.awt.Dimension(550, 495));
        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jPanel10.setBackground(new java.awt.Color(255, 255, 204));
        jPanel10.setPreferredSize(new java.awt.Dimension(500, 50));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel10);

        jPanel8.setBackground(new java.awt.Color(255, 255, 204));
        jPanel8.setLayout(new java.awt.BorderLayout(5, 0));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Cari :");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel8.add(jLabel6, java.awt.BorderLayout.WEST);

        jCari.setText("\n");
        jCari.setPreferredSize(new java.awt.Dimension(170, 34));
        jCari.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jCariFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jCariFocusLost(evt);
            }
        });
        jCari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCariMouseClicked(evt);
            }
        });
        jCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCariActionPerformed(evt);
            }
        });
        jCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jCariKeyTyped(evt);
            }
        });
        jPanel8.add(jCari, java.awt.BorderLayout.CENTER);

        jPanel9.add(jPanel8);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(500, 406));

        tb_mahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_mahasiswa.setPreferredSize(new java.awt.Dimension(500, 1000));
        tb_mahasiswa.setRowHeight(30);
        tb_mahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_mahasiswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_mahasiswa);

        jPanel9.add(jScrollPane1);

        javax.swing.GroupLayout pn_mahasiswaLayout = new javax.swing.GroupLayout(pn_mahasiswa);
        pn_mahasiswa.setLayout(pn_mahasiswaLayout);
        pn_mahasiswaLayout.setHorizontalGroup(
            pn_mahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_mahasiswaLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_mahasiswaLayout.setVerticalGroup(
            pn_mahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_mahasiswaLayout.createSequentialGroup()
                .addGroup(pn_mahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_profil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pn_nilai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pn_mahasiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_profil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pn_nilai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pn_mahasiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(content, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    int xx,xy;
    
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void btn_profilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_profilActionPerformed

        content.removeAll();
        content.repaint();
        content.revalidate();
        
        // Menambahkan panel
        content.add(pn_profil);
        content.repaint();
        content.revalidate();
        
    }//GEN-LAST:event_btn_profilActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        dispose();
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        Form_login form_login = new Form_login();
        form_login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_nilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nilaiActionPerformed
        content.removeAll();
        content.repaint();
        content.revalidate();
        
        // Menambahkan panel
        content.add(pn_nilai);
        content.repaint();
        content.revalidate();
    }//GEN-LAST:event_btn_nilaiActionPerformed

    private void btn_mahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mahasiswaActionPerformed

        content.removeAll();
        content.repaint();
        content.revalidate();
        
        // menambahkan panel
        content.add(pn_mahasiswa);
        content.repaint();
        content.revalidate();
        
        pn_mahasiswaAktif();
    }//GEN-LAST:event_btn_mahasiswaActionPerformed

    private void btn_maximizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_maximizeMouseClicked
        if(this.getExtendedState()!= Menu_utama.MAXIMIZED_BOTH) {
            this.setExtendedState(Menu_utama.MAXIMIZED_BOTH);
        } else {
            this.setExtendedState(Menu_utama.NORMAL);
        }
    }//GEN-LAST:event_btn_maximizeMouseClicked

    private void btn_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minimizeMouseClicked
        this.setState(Menu_utama.ICONIFIED);
    }//GEN-LAST:event_btn_minimizeMouseClicked

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        
        
        try {
            String query = "INSERT INTO mahasiswa(nama_mahasiswa,nim,jurusan,alamat) VALUES(?, ?, ?, ?)";
            PreparedStatement pst = conn.prepareStatement(query);
            pst.setString(1,jNama.getText());
            pst.setString(2,jNim.getText());
            pst.setString(3,(String) jJurusan.getSelectedItem());
            pst.setString(4,jAlamat.getText());
            
            if(jNama.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Fill out nama!", "Validasi", JOptionPane.ERROR_MESSAGE);
            } else if(jNim.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Fill out NIM!", "Validasi", JOptionPane.ERROR_MESSAGE);
            } else if(jAlamat.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Fill out alamat!", "Validasi", JOptionPane.ERROR_MESSAGE);
            } else {
                int rowInserted = pst.executeUpdate();
                if(rowInserted > 0) {
                    JOptionPane.showMessageDialog(null,"Add data successfull!");
                    getData();
                    resetData();
                    btnNonAktif();
                    btnAktif();
                }
            }
            
            pst.close();
            
        } catch(Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        resetData();
        btnAktif();
        btnNonAktif();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        int selectedRow = tb_mahasiswa.getSelectedRow();
        
        int id = Integer.parseInt(tb_mahasiswa.getValueAt(selectedRow, 0).toString()); // ubah dulu tipe data objek nya ke string (toString()), baru ubah String ke int (Integer.parseInt())
        
        if(selectedRow == -1) { // artinya jika tidak ada tabel yang diklik
            JOptionPane.showMessageDialog(null,"Select row first!", "validasi",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try{
            String query = "UPDATE mahasiswa SET nama_mahasiswa = ?, nim = ?, jurusan = ?, alamat = ? WHERE id_mahasiswa = ?";
            PreparedStatement pst = conn.prepareStatement(query);
            pst.setString(1, jNama.getText());
            pst.setString(2, jNim.getText());
            pst.setString(3, (String) jJurusan.getSelectedItem());
            pst.setString(4, jAlamat.getText());
            pst.setInt(5, id);
            
             if(jNama.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Fill out nama!", "Validasi", JOptionPane.ERROR_MESSAGE);
            } else if(jNim.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Fill out NIM!", "Validasi", JOptionPane.ERROR_MESSAGE);
            } else if(jAlamat.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Fill out alamat!", "Validasi", JOptionPane.ERROR_MESSAGE);
            } else {
                int rowUpdate = pst.executeUpdate();
                if(rowUpdate > 0) {
                    JOptionPane.showMessageDialog(null,"Update data successfull!");
                    getData();
                    resetData();
                    btnNonAktif();
                    btnAktif();
                }
            }
             
            pst.close();
            
        } catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        int selectedRow = tb_mahasiswa.getSelectedRow();
        
        if(selectedRow == -1) { // artinya jika tidak ada tabel yang diklik
            JOptionPane.showMessageDialog(null,"Select row first!", "validasi",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(null,"Apakah yakin ingin menghapus?", "konfirmasi", JOptionPane.YES_NO_OPTION);
        if(confirm == JOptionPane.YES_OPTION){
            int id = Integer.parseInt(tb_mahasiswa.getValueAt(selectedRow, 0).toString());
            
            try {
                String query = "DELETE FROM mahasiswa WHERE id_mahasiswa = ?";
                PreparedStatement pst = conn.prepareStatement(query);
                pst.setInt(1,id);
                
                int rowUpdate = pst.executeUpdate();
                
                if(rowUpdate > 0) {
                    JOptionPane.showMessageDialog(null,"Delete data successfull!");
                    getData();
                    resetData();
                }
            } catch(Exception e) {
                e.printStackTrace();
            }
            btnNonAktif();
            btnAktif();
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void jCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCariActionPerformed

    private void jCariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCariKeyTyped
        DefaultTableModel model = (DefaultTableModel) tb_mahasiswa.getModel();
        model.setRowCount(0);
        
        String cari = jCari.getText();
                
        try {
            String query = "SELECT * FROM mahasiswa WHERE nama_mahasiswa LIKE ? OR nim LIKE ? OR jurusan LIKE ? OR alamat LIKE ?";
            PreparedStatement pst = conn.prepareStatement(query);
            pst.setString(1,"%" + cari + "%");
            pst.setString(2,"%" + cari + "%");
            pst.setString(3,"%" + cari + "%");
            pst.setString(4,"%" + cari + "%");
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()) {
                Object[] rowData = {
                    rs.getInt("id_mahasiswa"),
                    rs.getString("nama_mahasiswa"),
                    rs.getString("nim"),
                    rs.getString("jurusan"),
                    rs.getString("alamat")
                };
                
                model.addRow(rowData);
                
                // Menyembunyikan kolom ID (kolom pertama)
                tb_mahasiswa.getColumnModel().getColumn(0).setMinWidth(0);
                tb_mahasiswa.getColumnModel().getColumn(0).setMaxWidth(0);
                tb_mahasiswa.getColumnModel().getColumn(0).setWidth(0);
            }
            
            rs.close();
            pst.close();
            
        } catch(Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jCariKeyTyped

    private void jCariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCariMouseClicked
       
    }//GEN-LAST:event_jCariMouseClicked

    private void jCariFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jCariFocusGained
       
    }//GEN-LAST:event_jCariFocusGained

    private void jCariFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jCariFocusLost
        
    }//GEN-LAST:event_jCariFocusLost

    private void jNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNamaActionPerformed

    private void jJurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jJurusanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jJurusanActionPerformed

    private void tb_mahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_mahasiswaMouseClicked
                int selectedRow = tb_mahasiswa.getSelectedRow();

        if(selectedRow != -1) { // artinya jika ada data yang diklik
            int id = Integer.parseInt(tb_mahasiswa.getValueAt(selectedRow, 0).toString());
            String nama = tb_mahasiswa.getValueAt(selectedRow, 1).toString();
            String nim = tb_mahasiswa.getValueAt(selectedRow, 2).toString();
            String jurusan = tb_mahasiswa.getValueAt(selectedRow, 3).toString();
            String alamat = tb_mahasiswa.getValueAt(selectedRow, 4).toString();

            jNama.setText(nama);
            jNim.setText(nim);
            jJurusan.setSelectedItem(jurusan);
            jAlamat.setText(alamat);

            btn_tambah.setEnabled(false);
            btn_edit.setEnabled(true);
            btn_hapus.setEnabled(true);
        }
    }//GEN-LAST:event_tb_mahasiswaMouseClicked
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_utama("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_mahasiswa;
    private javax.swing.JLabel btn_maximize;
    private javax.swing.JLabel btn_minimize;
    private javax.swing.JButton btn_nilai;
    private javax.swing.JButton btn_profil;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JPanel content;
    private javax.swing.JPanel header;
    private javax.swing.JTextField jAlamat;
    private javax.swing.JTextField jCari;
    private javax.swing.JComboBox<String> jJurusan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jNama;
    private javax.swing.JTextField jNim;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel name_website;
    private javax.swing.JPanel pn_mahasiswa;
    private javax.swing.JPanel pn_nilai;
    private javax.swing.JPanel pn_profil;
    private javax.swing.JLabel pnblogo;
    private javax.swing.JPanel sidebar;
    private javax.swing.JTable tb_mahasiswa;
    private javax.swing.JLabel txt_nilai;
    private javax.swing.JLabel txt_profil;
    // End of variables declaration//GEN-END:variables

}
