/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pbolanjut;



public class Menu_utama extends javax.swing.JFrame {

    /**
     * Creates new form Menu_utama
     */
    
 
    public Menu_utama(String username) {
        initComponents();
    
        txt_profil.setText("Welcome " + username);
        ResizeImage.setImageToLabel(pnblogo, "/pbolanjut/img/Logo-Politeknik-Negeri-Bali.png", 100, 100);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JPanel();
        pnblogo = new javax.swing.JLabel();
        name_website = new javax.swing.JLabel();
        btn_maximize = new javax.swing.JLabel();
        btn_minimize = new javax.swing.JLabel();
        sidebar = new javax.swing.JPanel();
        btn_profil = new javax.swing.JButton();
        btn_nilai = new javax.swing.JButton();
        btn_matkul = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        content = new javax.swing.JPanel();
        pn_profil = new javax.swing.JPanel();
        txt_profil = new javax.swing.JLabel();
        pn_nilai = new javax.swing.JPanel();
        txt_nilai = new javax.swing.JLabel();
        pn_matkul = new javax.swing.JPanel();
        txt_matkul = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        header.setBackground(new java.awt.Color(0, 153, 153));

        pnblogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbolanjut/img/Logo-Politeknik-Negeri-Bali.png"))); // NOI18N

        name_website.setBackground(new java.awt.Color(153, 153, 153));
        name_website.setFont(new java.awt.Font("Kristen ITC", 1, 29)); // NOI18N
        name_website.setForeground(new java.awt.Color(255, 255, 102));
        name_website.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name_website.setText("PNB WEBSITE CUY");
        name_website.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btn_maximize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbolanjut/img/maximize.png"))); // NOI18N
        btn_maximize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_maximizeMouseClicked(evt);
            }
        });

        btn_minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbolanjut/img/minus.png"))); // NOI18N
        btn_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_minimizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(pnblogo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                        .addComponent(name_website, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(148, 148, 148))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                        .addComponent(btn_minimize)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_maximize)
                        .addContainerGap())))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(name_website))
                    .addGroup(headerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnblogo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_maximize)
                            .addComponent(btn_minimize))))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(header, java.awt.BorderLayout.PAGE_START);

        sidebar.setBackground(new java.awt.Color(204, 204, 204));

        btn_profil.setBackground(new java.awt.Color(255, 255, 255));
        btn_profil.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btn_profil.setForeground(new java.awt.Color(153, 153, 153));
        btn_profil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbolanjut/img/user.png"))); // NOI18N
        btn_profil.setText("Profil");
        btn_profil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_profilActionPerformed(evt);
            }
        });

        btn_nilai.setBackground(new java.awt.Color(255, 255, 255));
        btn_nilai.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btn_nilai.setForeground(new java.awt.Color(153, 153, 153));
        btn_nilai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbolanjut/img/point.png"))); // NOI18N
        btn_nilai.setText("Nilai");
        btn_nilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nilaiActionPerformed(evt);
            }
        });

        btn_matkul.setBackground(new java.awt.Color(255, 255, 255));
        btn_matkul.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btn_matkul.setForeground(new java.awt.Color(153, 153, 153));
        btn_matkul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbolanjut/img/open-book.png"))); // NOI18N
        btn_matkul.setText("Matkul");
        btn_matkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_matkulActionPerformed(evt);
            }
        });

        btn_logout.setBackground(new java.awt.Color(255, 255, 255));
        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbolanjut/img/logout.png"))); // NOI18N
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        btn_exit.setBackground(new java.awt.Color(255, 255, 255));
        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pbolanjut/img/cross.png"))); // NOI18N
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_matkul, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_profil, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_nilai, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebarLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebarLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(btn_profil, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btn_nilai, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btn_matkul, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        getContentPane().add(sidebar, java.awt.BorderLayout.LINE_START);

        content.setBackground(new java.awt.Color(255, 255, 255));

        pn_profil.setBackground(new java.awt.Color(255, 255, 255));

        txt_profil.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        txt_profil.setForeground(new java.awt.Color(0, 0, 0));
        txt_profil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_profil.setText("PROFIL");

        javax.swing.GroupLayout pn_profilLayout = new javax.swing.GroupLayout(pn_profil);
        pn_profil.setLayout(pn_profilLayout);
        pn_profilLayout.setHorizontalGroup(
            pn_profilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_profilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_profil, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE))
        );
        pn_profilLayout.setVerticalGroup(
            pn_profilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_profilLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(txt_profil, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pn_nilai.setBackground(new java.awt.Color(255, 204, 204));

        txt_nilai.setBackground(new java.awt.Color(255, 255, 255));
        txt_nilai.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        txt_nilai.setForeground(new java.awt.Color(0, 0, 0));
        txt_nilai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_nilai.setText("NILAI");

        javax.swing.GroupLayout pn_nilaiLayout = new javax.swing.GroupLayout(pn_nilai);
        pn_nilai.setLayout(pn_nilaiLayout);
        pn_nilaiLayout.setHorizontalGroup(
            pn_nilaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_nilaiLayout.createSequentialGroup()
                .addContainerGap(224, Short.MAX_VALUE)
                .addComponent(txt_nilai, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(203, 203, 203))
        );
        pn_nilaiLayout.setVerticalGroup(
            pn_nilaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_nilaiLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(txt_nilai, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(184, Short.MAX_VALUE))
        );

        pn_matkul.setBackground(new java.awt.Color(255, 255, 204));

        txt_matkul.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        txt_matkul.setForeground(new java.awt.Color(0, 0, 0));
        txt_matkul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_matkul.setText("MATKUL");

        javax.swing.GroupLayout pn_matkulLayout = new javax.swing.GroupLayout(pn_matkul);
        pn_matkul.setLayout(pn_matkulLayout);
        pn_matkulLayout.setHorizontalGroup(
            pn_matkulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_matkulLayout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(txt_matkul, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(185, Short.MAX_VALUE))
        );
        pn_matkulLayout.setVerticalGroup(
            pn_matkulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_matkulLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(txt_matkul, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_profil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pn_nilai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pn_matkul, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_profil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pn_nilai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(contentLayout.createSequentialGroup()
                    .addComponent(pn_matkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(content, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    int xx,xy;
    
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void btn_profilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_profilActionPerformed

        content.removeAll();
        content.repaint();
        content.revalidate();
        
        // Menambahkan panel
        content.add(pn_profil);
        content.repaint();
        content.revalidate();
    }//GEN-LAST:event_btn_profilActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        dispose();
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        Form_login form_login = new Form_login();
        form_login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_nilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nilaiActionPerformed
        content.removeAll();
        content.repaint();
        content.revalidate();
        
        // Menambahkan panel
        content.add(pn_nilai);
        content.repaint();
        content.revalidate();
    }//GEN-LAST:event_btn_nilaiActionPerformed

    private void btn_matkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_matkulActionPerformed

        content.removeAll();
        content.repaint();
        content.revalidate();
        
        // menambahkan panel
        content.add(pn_matkul);
        content.repaint();
        content.revalidate();
    }//GEN-LAST:event_btn_matkulActionPerformed

    private void btn_maximizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_maximizeMouseClicked
        if(this.getExtendedState()!= Menu_utama.MAXIMIZED_BOTH) {
            this.setExtendedState(Menu_utama.MAXIMIZED_BOTH);
        } else {
            this.setExtendedState(Menu_utama.NORMAL);
        }
    }//GEN-LAST:event_btn_maximizeMouseClicked

    private void btn_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minimizeMouseClicked
        this.setState(Menu_utama.ICONIFIED);
    }//GEN-LAST:event_btn_minimizeMouseClicked
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_utama("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_matkul;
    private javax.swing.JLabel btn_maximize;
    private javax.swing.JLabel btn_minimize;
    private javax.swing.JButton btn_nilai;
    private javax.swing.JButton btn_profil;
    private javax.swing.JPanel content;
    private javax.swing.JPanel header;
    private javax.swing.JLabel name_website;
    private javax.swing.JPanel pn_matkul;
    private javax.swing.JPanel pn_nilai;
    private javax.swing.JPanel pn_profil;
    private javax.swing.JLabel pnblogo;
    private javax.swing.JPanel sidebar;
    private javax.swing.JLabel txt_matkul;
    private javax.swing.JLabel txt_nilai;
    private javax.swing.JLabel txt_profil;
    // End of variables declaration//GEN-END:variables

}
